"""
The review report — the conversion tool's primary output (BAL-11).

The data files are a side effect of an auditable process.  This module renders
that audit: what was chosen, which requirement chose it, how confident the tool
is, which flags it could not map, and every number it had to invent.

Copyright (c) 2026 ZangbandTK contributors

This work is free software; you can redistribute it and/or modify it under the
terms of either:

a) the GNU General Public License as published by the Free Software
   Foundation, version 2, or

b) the "Angband licence":
   This software may be copied and distributed for educational, research,
   and not for profit purposes provided that this copyright and statement
   are included in all such copies.  Other copyrights may also apply.
"""

from __future__ import annotations

from collections import Counter
from dataclasses import dataclass, field

from rules import CONVERTED, DERIVED, EXACT, INVENTED, ORDER, Value


@dataclass
class Converted:
    """One converted entry and the provenance of each field."""

    name: str
    source_index: int
    fields: dict[str, Value] = field(default_factory=dict)
    unmapped_flags: list[str] = field(default_factory=list)
    overridden: list[str] = field(default_factory=list)
    #: (flag, disposition, reason) for flags not carried into the output
    flag_dispositions: list[tuple[str, str, str]] = field(default_factory=list)
    #: notes about vocabulary translated between the two data models
    translations: list[str] = field(default_factory=list)

    @property
    def worst(self) -> str:
        if not self.fields:
            return EXACT
        return max((v.confidence for v in self.fields.values()), key=lambda c: ORDER[c])

    @property
    def invented(self) -> dict[str, Value]:
        return {k: v for k, v in self.fields.items() if v.confidence == INVENTED}


@dataclass
class Report:
    title: str
    source: str
    target: str
    lethality: str
    items: list[Converted] = field(default_factory=list)
    notes: list[str] = field(default_factory=list)
    skipped: list[tuple[str, str]] = field(default_factory=list)

    def render(self) -> str:
        out: list[str] = []
        w = out.append

        w(f"# {self.title}")
        w("")
        w(f"- **Source:** `{self.source}`")
        w(f"- **Target:** `{self.target}`")
        w(f"- **Lethality scalar (BAL-13):** {self.lethality}")
        w(f"- **Entries converted:** {len(self.items)}")
        if self.skipped:
            w(f"- **Entries skipped:** {len(self.skipped)}")
        w("")
        w("> Generated by `tools/zconv`. Deterministic: the same inputs produce a")
        w("> byte-identical report (BAL-12). Review the *Invented* section before")
        w("> accepting any generated data file.")
        w("")

        # --- confidence summary
        counts = Counter(item.worst for item in self.items)
        w("## Confidence")
        w("")
        w("Each entry is reported at its weakest field.")
        w("")
        w("| Confidence | Entries | Meaning |")
        w("|---|---:|---|")
        for level, meaning in (
            (EXACT, "same meaning and scale in both versions; taken unchanged"),
            (CONVERTED, "transformed by a verified rule (a scale or units change)"),
            (DERIVED, "computed from 4.2's own curve; plausible, unverified"),
            (INVENTED, "**no basis in either source — must be reviewed**"),
        ):
            w(f"| {level} | {counts.get(level, 0)} | {meaning} |")
        w("")

        # --- rules applied
        rule_counts: Counter[str] = Counter()
        for item in self.items:
            for value in item.fields.values():
                rule_counts[value.rule] += 1
        if rule_counts:
            w("## Rules applied")
            w("")
            w("| Requirement | Field values produced |")
            w("|---|---:|")
            for rule, count in sorted(rule_counts.items()):
                w(f"| {rule} | {count} |")
            w("")

        # --- invented numbers (BAL-11's explicit requirement)
        invented = [(item, item.invented) for item in self.items if item.invented]
        w("## Invented values")
        w("")
        if not invented:
            w("None. Every field traced to a source or a fitted curve.")
        else:
            w(f"**{sum(len(v) for _, v in invented)} values across "
              f"{len(invented)} entries had no basis in either source.** "
              "These are the tool's guesses and carry no authority.")
            w("")
            w("| Entry | Field | Value | Rule | Why |")
            w("|---|---|---:|---|---|")
            for item, fields in invented:
                for name, value in sorted(fields.items()):
                    w(f"| {item.name} | `{name}` | {value.value} | {value.rule} | "
                      f"{value.note} |")
        w("")

        # --- flag resolution (BAL-10)
        counts: Counter[str] = Counter()
        reasons: dict[str, tuple[str, str]] = {}
        for item in self.items:
            for flag, disposition, reason in item.flag_dispositions:
                counts[flag] += 1
                reasons[flag] = (disposition, reason)
            counts.update(item.unmapped_flags)
            for flag in item.unmapped_flags:
                reasons.setdefault(flag, ("unresolved", "no disposition recorded"))

        w("## Flag resolution")
        w("")
        if not counts:
            w("Every source flag was carried into the output, renamed, or converted "
              "to a 4.2 field.")
        else:
            by_disposition: dict[str, list[tuple[str, int, str]]] = {}
            for flag, count in counts.items():
                disposition, reason = reasons[flag]
                by_disposition.setdefault(disposition, []).append((flag, count, reason))

            unresolved = len(by_disposition.get("unresolved", []))
            w(f"{len(counts)} distinct flags were not carried directly into the output. "
              "Per BAL-10 each is mapped, implemented, or explicitly rejected with a "
              "reason.")
            w("")
            if unresolved:
                w(f"⚠️ **{unresolved} flags have no recorded disposition.** Add them to "
                  "`flagmap.toml` before accepting this conversion.")
            else:
                w("✅ **Every flag has a recorded disposition.**")
            w("")

            headings = {
                "reject": "Rejected — no meaning under 4.2's model",
                "defer": "Deferred — real mechanic, blocked on a milestone",
                "implement": "To implement — mechanic 4.2 lacks and we want",
                "manual": "Manual — needs information the flag does not carry",
                "unresolved": "⚠️ Unresolved",
            }
            for disposition in ("unresolved", "manual", "implement", "defer", "reject"):
                rows = by_disposition.get(disposition)
                if not rows:
                    continue
                w(f"### {headings[disposition]}")
                w("")
                w("| Flag | Monsters | Reason |")
                w("|---|---:|---|")
                for flag, count, reason in sorted(rows, key=lambda r: (-r[1], r[0])):
                    tidy = " ".join(reason.split())
                    w(f"| `{flag}` | {count} | {tidy} |")
                w("")
        w("")

        # --- vocabulary translation
        translated = [(i.name, i.translations) for i in self.items
                      if i.translations]
        w("## Vocabulary translated")
        w("")
        if not translated:
            w("None. Every method, effect and name existed in both models.")
        else:
            dropped = [(n, notes) for n, notes in translated
                       if any("dropped" in note for note in notes)]
            w(f"{len(translated)} entries used vocabulary that differs between "
              "the two data models.")
            w("")
            if dropped:
                w(f"⚠️ **{len(dropped)} entries had something dropped entirely** "
                  "because no equivalent exists and none is mapped. Review these "
                  "first — a monster that loses every blow is left unable to "
                  "attack.")
                w("")
            w("| Entry | Translation |")
            w("|---|---|")
            for name, notes in translated:
                for note in notes:
                    mark = "⚠️ " if "dropped" in note else ""
                    w(f"| {name} | {mark}{' '.join(note.split())} |")
        w("")

        # --- overrides (BAL-12)
        overridden = [(i.name, i.overridden) for i in self.items if i.overridden]
        w("## Overrides applied")
        w("")
        if not overridden:
            w("None. No hand-tuned values in `overrides.toml` matched this run.")
        else:
            w("Hand-edits from `overrides.toml`, reapplied on every run so that "
              "re-conversion never silently discards tuning work (BAL-12).")
            w("")
            w("| Entry | Fields |")
            w("|---|---|")
            for name, fields in overridden:
                w(f"| {name} | {', '.join(f'`{f}`' for f in sorted(fields))} |")
        w("")

        if self.skipped:
            w("## Skipped")
            w("")
            w("| Entry | Reason |")
            w("|---|---|")
            for name, reason in self.skipped:
                w(f"| {name} | {reason} |")
            w("")

        if self.notes:
            w("## Notes")
            w("")
            for note in self.notes:
                w(f"- {note}")
            w("")

        return "\n".join(out) + "\n"
