"""
The review report — the conversion tool's primary output (BAL-11).

The data files are a side effect of an auditable process.  This module renders
that audit: what was chosen, which requirement chose it, how confident the tool
is, which flags it could not map, and every number it had to invent.

Copyright (c) 2026 ZangbandZK contributors

This work is free software; you can redistribute it and/or modify it under the
terms of either:

a) the GNU General Public License as published by the Free Software
   Foundation, version 2, or

b) the "Angband licence":
   This software may be copied and distributed for educational, research,
   and not for profit purposes provided that this copyright and statement
   are included in all such copies.  Other copyrights may also apply.
"""

from __future__ import annotations

from collections import Counter
from dataclasses import dataclass, field

from rules import CONVERTED, DERIVED, EXACT, INVENTED, ORDER, Value


@dataclass
class Converted:
    """One converted entry and the provenance of each field."""

    name: str
    source_index: int
    fields: dict[str, Value] = field(default_factory=dict)
    unmapped_flags: list[str] = field(default_factory=list)
    overridden: list[str] = field(default_factory=list)

    @property
    def worst(self) -> str:
        if not self.fields:
            return EXACT
        return max((v.confidence for v in self.fields.values()), key=lambda c: ORDER[c])

    @property
    def invented(self) -> dict[str, Value]:
        return {k: v for k, v in self.fields.items() if v.confidence == INVENTED}


@dataclass
class Report:
    title: str
    source: str
    target: str
    lethality: str
    items: list[Converted] = field(default_factory=list)
    notes: list[str] = field(default_factory=list)
    skipped: list[tuple[str, str]] = field(default_factory=list)

    def render(self) -> str:
        out: list[str] = []
        w = out.append

        w(f"# {self.title}")
        w("")
        w(f"- **Source:** `{self.source}`")
        w(f"- **Target:** `{self.target}`")
        w(f"- **Lethality scalar (BAL-13):** {self.lethality}")
        w(f"- **Entries converted:** {len(self.items)}")
        if self.skipped:
            w(f"- **Entries skipped:** {len(self.skipped)}")
        w("")
        w("> Generated by `tools/zconv`. Deterministic: the same inputs produce a")
        w("> byte-identical report (BAL-12). Review the *Invented* section before")
        w("> accepting any generated data file.")
        w("")

        # --- confidence summary
        counts = Counter(item.worst for item in self.items)
        w("## Confidence")
        w("")
        w("Each entry is reported at its weakest field.")
        w("")
        w("| Confidence | Entries | Meaning |")
        w("|---|---:|---|")
        for level, meaning in (
            (EXACT, "same meaning and scale in both versions; taken unchanged"),
            (CONVERTED, "transformed by a verified rule (a scale or units change)"),
            (DERIVED, "computed from 4.2's own curve; plausible, unverified"),
            (INVENTED, "**no basis in either source — must be reviewed**"),
        ):
            w(f"| {level} | {counts.get(level, 0)} | {meaning} |")
        w("")

        # --- rules applied
        rule_counts: Counter[str] = Counter()
        for item in self.items:
            for value in item.fields.values():
                rule_counts[value.rule] += 1
        if rule_counts:
            w("## Rules applied")
            w("")
            w("| Requirement | Field values produced |")
            w("|---|---:|")
            for rule, count in sorted(rule_counts.items()):
                w(f"| {rule} | {count} |")
            w("")

        # --- invented numbers (BAL-11's explicit requirement)
        invented = [(item, item.invented) for item in self.items if item.invented]
        w("## Invented values")
        w("")
        if not invented:
            w("None. Every field traced to a source or a fitted curve.")
        else:
            w(f"**{sum(len(v) for _, v in invented)} values across "
              f"{len(invented)} entries had no basis in either source.** "
              "These are the tool's guesses and carry no authority.")
            w("")
            w("| Entry | Field | Value | Rule | Why |")
            w("|---|---|---:|---|---|")
            for item, fields in invented:
                for name, value in sorted(fields.items()):
                    w(f"| {item.name} | `{name}` | {value.value} | {value.rule} | "
                      f"{value.note} |")
        w("")

        # --- unmapped flags (BAL-10)
        flag_counts: Counter[str] = Counter()
        for item in self.items:
            flag_counts.update(item.unmapped_flags)
        w("## Unmapped flags")
        w("")
        if not flag_counts:
            w("None. Every source flag mapped to a 4.2 equivalent.")
        else:
            w(f"**{len(flag_counts)} distinct flags have no 4.2 equivalent.** Per BAL-10 "
              "each must be mapped, implemented, or explicitly rejected with a reason — "
              "never silently dropped.")
            w("")
            w("| Flag | Entries affected |")
            w("|---|---:|")
            for flag, count in sorted(flag_counts.items(), key=lambda kv: (-kv[1], kv[0])):
                w(f"| `{flag}` | {count} |")
        w("")

        # --- overrides (BAL-12)
        overridden = [(i.name, i.overridden) for i in self.items if i.overridden]
        w("## Overrides applied")
        w("")
        if not overridden:
            w("None. No hand-tuned values in `overrides.toml` matched this run.")
        else:
            w("Hand-edits from `overrides.toml`, reapplied on every run so that "
              "re-conversion never silently discards tuning work (BAL-12).")
            w("")
            w("| Entry | Fields |")
            w("|---|---|")
            for name, fields in overridden:
                w(f"| {name} | {', '.join(f'`{f}`' for f in sorted(fields))} |")
        w("")

        if self.skipped:
            w("## Skipped")
            w("")
            w("| Entry | Reason |")
            w("|---|---|")
            for name, reason in self.skipped:
                w(f"| {name} | {reason} |")
            w("")

        if self.notes:
            w("## Notes")
            w("")
            for note in self.notes:
                w(f"- {note}")
            w("")

        return "\n".join(out) + "\n"
