#!/usr/bin/env python3
"""
Give the imported monsters a tile to stand in until they have their own.

ZangbandTK adds 391 monsters that Angband does not have, and not one of them
appears in any of the shipped tilesets -- so in graphics mode they render as ASCII
letters among the pictures.  Most of them are ordinary creatures that look like
something already drawn: a chaos hound is a hound, a serpent man is a snake.

For each imported monster this finds an Angband monster that shares its `base:`,
prefers one that also shares its `color:`, and among those picks the one nearest
in `depth:` -- so a deep wolf borrows from a wolf rather than from a puppy.  The
tile coordinates are copied verbatim from the tileset's own prf lines, never
computed, because the renderer wraps an out-of-range cell with `% pict_rows`
instead of complaining: a wrong coordinate draws the wrong picture in silence.

UNIQUES ARE DELIBERATELY LEFT ALONE.  A borrowed tile for a common monster is a
reasonable stand-in; for a unique it is a lie about the thing the player most
wants to recognise, and the lie lands badly here.  Matched by base and depth,
Oberon of Amber, Dworkin and Mandor all come out wearing the Mouth of Sauron's
face -- which is precisely the drift this project exists to undo.  A letter says
"no picture yet"; a wrong portrait says something false.

Re-runnable: it rewrites its own output file and adds its include line once.

    scripts/tiles/borrow-tiles.py [--dry-run] [--check]

--check re-reads what was written and verifies it against the two ways this
can go wrong silently: lookup_monster() falls back to a substring match, so a
misspelled name binds to whatever contains it; and the renderer takes a cell
index modulo the sheet size, so an out-of-range coordinate draws some other
picture rather than failing.  Both are checked by construction here -- names
come from the data files and coordinates are copied from existing lines -- and
the check is what proves it stayed that way.
"""

import os
import re
import sys

ROOT = os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', '..')
TILES = os.path.join(ROOT, 'lib', 'tiles')
DATA = os.path.join(ROOT, 'lib', 'gamedata')
OUTPUT = 'graf-ztk.prf'

HEADER = """# %s -- stand-in tiles for the things this project added.
#
# GENERATED by scripts/tiles/borrow-tiles.py.  Do not edit by hand: re-running
# the script overwrites this file.  Every line borrows a picture the tileset
# already contains, and names in a comment what it was taken from, so a
# wrong-looking tile can be traced without running anything.
#
# Monsters match on `base:`, preferring the same `color:` and then the nearest
# `depth:`.  Objects match on `type:`, preferring the same colour and then the
# nearest `level:`.  Traps match on the code trap.txt groups them under, and
# are borrowed whole -- every lighting state the donor has and no others.
#
# These are placeholders.  Replacing one with real art means deleting its line
# here and adding a proper mapping to %s.
#
# Uniques are deliberately absent -- they render as text until they have art of
# their own, because a borrowed portrait on a named character says something
# false about that character.  Nothing else here makes a claim that strong: a
# fish drawn as a snake says only that it is long and legless.
"""

MONSTERS = ['monster.txt', 'monster.zangband.txt', 'monster.zangbandtk.txt']

# Bases no Angband monster has, and the nearest one that exists.
#
# Without these, a fish is the letter 'f' in the middle of a drawn dungeon,
# because choose_donor() requires a shared base and there is no fish in
# Angband to share it with.  Twenty of the imported monsters are fish and
# eleven are wall monsters; between them they are two thirds of everything the
# script used to give up on.
#
# This is a different judgement from the one about uniques.  A borrowed
# portrait on a named character asserts something false about that character.
# A fish drawn as a snake asserts only that it is long and legless, which it
# is -- and the alternative is not a better picture, it is no picture.
# Traps that are not pictures.  'no trap' is the absence of one and 'door
# lock' is a property of a door, not something drawn on the floor beside it.
TRAP_SKIP = ('no trap', 'door lock')

# Trap codes with no drawn sibling, and the code to borrow from instead.
TRAP_ALIAS = {
    # Both are the player's own marks on the floor rather than hazards.
    'decoy': ('glyph of warding',),
    # A web is a hazard with no relative in the shipped sets, so it takes the
    # generic hazard mark.
    'web': ('trap', 'strange rune'),
}

# Terrain with no art, and what to draw it as.  Neither of these is a
# placeholder: a secret door is a wall until it is found, and the way down into
# the dungeon is a way down.
FEAT_ALIAS = {
    'SECRET': 'GRANITE',
    'DUNGEON': 'MORE',
}

BASE_ALIAS = {
    'fish': ('snake', 'worm'),
    'wall monster': ('xorn', 'mimic', 'golem'),
    'animated weapon': ('golem', 'mimic'),
    # Angband has tree monsters but no shipped tileset draws one, so the ents
    # and huorns had nothing to take.  A giant is the nearest thing that is
    # drawn: tall, slow, and roughly person-shaped.
    'tree': ('giant', 'humanoid'),
}


def read_monsters(filename):
    """name -> {base, color, depth, unique}, in file order."""
    out = {}
    current = None

    with open(os.path.join(DATA, filename), encoding='utf-8', errors='replace') as f:
        for line in f:
            line = line.rstrip('\n')
            if line.startswith('name:'):
                current = line[5:].strip()
                out[current] = {'base': None, 'color': None, 'depth': 0,
                                'unique': False}
            elif current is None:
                continue
            elif line.startswith('base:'):
                out[current]['base'] = line[5:].strip()
            elif line.startswith('color:'):
                out[current]['color'] = line[6:].strip()
            elif line.startswith('depth:'):
                try:
                    out[current]['depth'] = int(line[6:].strip())
                except ValueError:
                    pass
            elif line.startswith('flags:') and 'UNIQUE' in line:
                out[current]['unique'] = True

    return out


def read_prf_chain(directory, filename, seen=None, skip_generated=True):
    """
    Every assignment in a prf and the files it includes, by directive.

    Returns {'monster': {name: (attr, char)}, 'object': ..., 'trap': ...,
    'feat': ...}, with keys lowercased throughout because the engine compares
    them with my_stricmp and the shipped files do not agree on case: the prf
    files say "Filthy street urchin" where monster.txt says "filthy street
    urchin".  A case-sensitive reader concludes that a tileset drawing all of
    Angband is missing six hundred monsters.

    `trap` and `feat` keep their lighting keyword in the key, because a donor
    can be mapped for some lighting states and not others and the borrowed
    lines have to match what is actually there.

    The generated file is skipped by default, because the tileset's own prf now
    includes it: without that, a second run sees everything the first run wrote
    as art that already exists, decides there is nothing left to do, and empties
    the file it wrote yesterday.
    """
    if seen is None:
        seen = set()

    empty = {k: {} for k in ('monster', 'object', 'trap', 'feat')}

    if skip_generated and os.path.basename(filename) == OUTPUT:
        return empty

    path = os.path.join(TILES, directory, filename)
    if path in seen or not os.path.exists(path):
        return empty
    seen.add(path)

    tiles = empty
    with open(path, encoding='utf-8', errors='replace') as f:
        for line in f:
            line = line.strip()

            m = re.match(r'^(monster|object|trap|feat):(.+):'
                         r'(0x[0-9A-Fa-f]+|\d+):(0x[0-9A-Fa-f]+|\d+)$', line)
            if m:
                tiles[m.group(1)][m.group(2).lower()] = (m.group(3), m.group(4))
                continue

            if line.startswith('%:'):
                more = read_prf_chain(directory, line[2:].strip(), seen,
                                      skip_generated)
                for kind in tiles:
                    tiles[kind].update(more[kind])

    return tiles


def read_tilesets():
    """(id, name, directory, pref) for each tileset in list.txt."""
    out = []
    entry = {}

    with open(os.path.join(TILES, 'list.txt'), encoding='utf-8') as f:
        for line in f:
            line = line.strip()
            if line.startswith('name:'):
                if entry.get('directory'):
                    out.append(entry)
                bits = line.split(':', 2)
                entry = {'id': bits[1], 'name': bits[2]}
            elif line.startswith('directory:'):
                entry['directory'] = line[10:].strip()
            elif line.startswith('pref:'):
                entry['pref'] = line[5:].strip()

    if entry.get('directory'):
        out.append(entry)

    return out


def choose_donor(want, candidates):
    """
    A monster to borrow a tile from, or None.

    Same base first -- a snake must not borrow from a dog.  Sharing the colour
    as well is much better, because the colour is most of what a small tile
    conveys.  Nearest depth breaks the tie, which is what stops a wolf unique
    from borrowing a scruffy little dog.

    Only if the base has no donor at all does BASE_ALIAS get a turn, and the
    result is reported separately: "as a snake, no fish exists" is a different
    claim from "as a wolf" and the generated file says which.
    """
    tried = [want['base']] + list(BASE_ALIAS.get(want['base'], ()))

    for n, base in enumerate(tried):
        same = [c for c in candidates
                if c[1]['base'] == base and c[1]['color'] == want['color']]
        exact = bool(same) and n == 0

        if not same:
            same = [c for c in candidates if c[1]['base'] == base]

        if not same:
            continue

        best = min(same, key=lambda c: abs(c[1]['depth'] - want['depth']))
        return best, exact, (n > 0)

    return None, False, False


def obj_name(fmt):
    """
    object.txt's `name:` as lookup_sval() will compare it.

    lookup_sval() runs each kind's name through obj_desc_name_format() before
    comparing, so `& Small wooden chest~` is looked up as "Small wooden chest".
    Writing the raw form produces a preference file that parses cleanly and
    resolves nothing, with no error of any kind: an sval that does not exist is
    simply a line that never fires.  Ported from obj_desc_name_format() in
    src/obj-desc.c with pluralise false and no modstr, which is how
    lookup_sval() calls it.
    """
    out, at = [], 0
    while at < len(fmt):
        ch = fmt[at]
        if ch == '&':
            while at < len(fmt) and fmt[at] in ' &':
                at += 1
            continue
        if ch == '~':
            at += 1
            continue
        if ch == '|':                       # kni|fe|ves| -> knife
            rest = fmt[at + 1:]
            first = rest.find('|')
            second = rest.find('|', first + 1) if first >= 0 else -1
            if first < 0 or second < 0:
                break
            out.append(rest[:first])
            at = at + 1 + second + 1
            continue
        out.append(ch)
        at += 1
    return ''.join(out)


def read_objects():
    """(tval, name) -> {color, level}, for every object kind that has a tval.

    Flavoured kinds are excluded.  Before it is identified a potion is its
    flavour and nothing else, so those are covered by flavor: lines, which
    every shipped tileset already has in full.
    """
    flavoured = set()
    kind = None
    with open(os.path.join(DATA, 'flavor.txt'), encoding='utf-8') as f:
        for line in f:
            if line.startswith('kind:'):
                flavoured.add(line.split(':')[1])

    out, name = {}, None
    current = {}
    with open(os.path.join(DATA, 'object.txt'), encoding='utf-8',
              errors='replace') as f:
        for line in f:
            line = line.rstrip('\n')
            if line.startswith('name:'):
                name = obj_name(line[5:].strip())
                current = {'color': None, 'level': 0, 'type': None}
            elif name is None:
                continue
            elif line.startswith('type:'):
                current['type'] = line[5:].strip()
                if current['type'] not in flavoured:
                    out[(current['type'], name)] = current
            elif line.startswith('graphics:'):
                current['color'] = line.split(':')[-1].strip()
            elif line.startswith('level:'):
                try:
                    current['level'] = int(line[6:].strip())
                except ValueError:
                    pass

    return out


def read_traps():
    """name -> {code, color}, for every trap that is drawn on the floor."""
    out, name = {}, None
    with open(os.path.join(DATA, 'trap.txt'), encoding='utf-8',
              errors='replace') as f:
        for line in f:
            line = line.rstrip('\n')
            if line.startswith('name:'):
                bits = line.split(':')
                if len(bits) < 3:
                    name = None
                    continue
                name = bits[2].strip()
                out[name] = {'code': bits[1].strip(), 'color': None}
            elif name and line.startswith('graphics:'):
                out[name]['color'] = line.split(':')[-1].strip()

    return out


def read_terrain_codes():
    """Every code: in terrain.txt, in file order."""
    return [l[5:].strip() for l
            in open(os.path.join(DATA, 'terrain.txt'), encoding='utf-8',
                    errors='replace')
            if l.startswith('code:')]


def check(tilesets):
    """
    Verify what was written, against the two ways this goes wrong in silence.

    lookup_monster() falls back to a substring match and lookup_sval() returns
    -1 without complaining, so a name that is wrong binds to the wrong thing or
    to nothing at all.  And the renderer takes a cell index modulo the sheet
    size rather than failing, so a coordinate that is not really in the sheet
    draws some other picture.

    Both are avoided by construction here -- names come from the data files and
    coordinates are copied from lines the tileset already uses -- and this is
    what proves it stayed that way.
    """
    names = set()
    for filename in MONSTERS:
        names.update(n.lower() for n in read_monsters(filename))
    svals = {('%s:%s' % k).lower() for k in read_objects()}
    trap_names = {n.lower() for n in read_traps()}
    feat_codes = {c.lower() for c in read_terrain_codes()}

    known = {'monster': names, 'object': svals, 'trap': trap_names,
             'feat': feat_codes}
    problems = 0

    for ts in tilesets:
        directory = ts['directory']
        path = os.path.join(TILES, directory, OUTPUT)
        if not os.path.exists(path):
            print("  %-12s nothing borrowed" % directory)
            continue

        # Every cell any other file in the set uses.  A borrowed coordinate
        # has to be one of these: the whole point is that the picture is
        # already there.
        cells = set()
        for other in sorted(os.listdir(os.path.join(TILES, directory))):
            if not other.endswith('.prf') or other == OUTPUT:
                continue
            for kind, got in read_prf_chain(directory, other).items():
                for coord in got.values():
                    cells.add((coord[0].lower(), coord[1].lower()))

        count = 0
        with open(path, encoding='utf-8') as f:
            for line in f:
                m = re.match(r'^(monster|object|trap|feat):(.+):'
                             r'(0x[0-9A-Fa-f]+):(0x[0-9A-Fa-f]+)\s*$', line)
                if not m:
                    continue
                count += 1
                kind, key = m.group(1), m.group(2)

                # trap: and feat: carry a lighting keyword the data does not.
                if kind in ('trap', 'feat'):
                    key = key.rsplit(':', 1)[0]

                if key.lower() not in known[kind]:
                    print("  %s: no such %s '%s'" % (directory, kind, key))
                    problems += 1

                if (m.group(3).lower(), m.group(4).lower()) not in cells:
                    print("  %s: %s:%s is not a cell any other line uses"
                          % (directory, m.group(3), m.group(4)))
                    problems += 1

        print("  %-12s %d lines checked" % (directory, count))

    print("\n%d problems" % problems)

    return 1 if problems else 0


def main():
    dry_run = '--dry-run' in sys.argv

    if '--check' in sys.argv:
        return check(read_tilesets())

    monsters = {}
    for name in MONSTERS:
        monsters.update(read_monsters(name))
    objects = read_objects()
    traps = read_traps()
    codes = read_terrain_codes()

    common = {n: v for n, v in monsters.items() if not v['unique']}
    uniques = [n for n, v in monsters.items() if v['unique']]

    print("%d monsters: %d ordinary, %d unique (left as text)"
          % (len(monsters), len(common), len(uniques)))
    print("%d objects, %d traps, %d terrain codes\n"
          % (len(objects), len(traps), len(codes)))

    for ts in read_tilesets():
        tiles = read_prf_chain(ts['directory'], ts['pref'])
        lines = []
        counts = {}

        # --- monsters ----------------------------------------------------
        candidates = [(n, v) for n, v in monsters.items()
                      if n.lower() in tiles['monster']]
        exact_n = alias_n = 0
        missed = []
        got = []

        for name, want in sorted(common.items()):
            if name.lower() in tiles['monster']:
                continue

            donor, exact, aliased = choose_donor(want, candidates)
            if not donor:
                missed.append(name)
                continue

            attr, char = tiles['monster'][donor[0].lower()]
            if exact:
                note = donor[0]
                exact_n += 1
            elif aliased:
                note = '%s (no %s is drawn)' % (donor[0], want['base'])
                alias_n += 1
            else:
                note = '%s (colour differs)' % donor[0]
            got.append(('# as %s' % note,
                        'monster:%s:%s:%s' % (name, attr, char)))

        counts['monster'] = len(got)
        if got:
            lines.append('\n##### Monsters #####')
            for comment, line in got:
                lines += ['', comment, line]

        # --- objects -----------------------------------------------------
        #
        # The same idea, matched on `type:` rather than `base:`, and on
        # `level:` rather than `depth:`.  These are almost all things this
        # project added -- new foods, a dragon scale mail, a throwing hammer --
        # and every one of them is a variant of something already drawn.
        got, obj_missed = [], []
        for (tval, name), want in sorted(objects.items()):
            if ('%s:%s' % (tval, name)).lower() in tiles['object']:
                continue

            pool = [(k, v) for k, v in objects.items()
                    if k[0] == tval
                    and ('%s:%s' % k).lower() in tiles['object']]
            if not pool:
                obj_missed.append('%s:%s' % (tval, name))
                continue

            same = [c for c in pool if c[1]['color'] == want['color']] or pool
            best = min(same, key=lambda c: abs(c[1]['level'] - want['level']))
            attr, char = tiles['object'][('%s:%s' % best[0]).lower()]
            got.append(('# as %s' % best[0][1],
                        'object:%s:%s:%s:%s' % (tval, name, attr, char)))

        counts['object'] = len(got)
        if got:
            lines.append('\n##### Objects #####')
            for comment, line in got:
                lines += ['', comment, line]

        # --- traps -------------------------------------------------------
        #
        # Keyed on the trap's own name because that is what the prf names, and
        # matched on the code, which is the group trap.txt puts it in.  A trap
        # is borrowed whole: every lighting state the donor is drawn for, and
        # no others, because a lighting state the tileset never mapped is not
        # one this file can invent.
        got, trap_missed = [], []
        for name, want in sorted(traps.items()):
            if name in TRAP_SKIP:
                continue
            if any(k.startswith(name.lower() + ':') for k in tiles['trap']):
                continue

            aliased = False
            pool = [n for n, v in traps.items()
                    if v['code'] == want['code'] and n != name
                    and any(k.startswith(n.lower() + ':')
                            for k in tiles['trap'])]
            if not pool:
                for alias in TRAP_ALIAS.get(want['code'], ()):
                    pool = [n for n, v in traps.items()
                            if v['code'] == alias
                            and any(k.startswith(n.lower() + ':')
                                    for k in tiles['trap'])]
                    if pool:
                        aliased = True
                        break
            if not pool:
                trap_missed.append(name)
                continue

            donor = sorted(pool)[0]
            cells = {k.rsplit(':', 1)[1]: v for k, v in tiles['trap'].items()
                     if k.startswith(donor.lower() + ':')}
            got.append(('# as %s%s' % (donor,
                                       ' (nothing like it is drawn)'
                                       if aliased else ''),
                        ['trap:%s:%s:%s:%s' % (name, light, c[0], c[1])
                         for light, c in sorted(cells.items())]))

        counts['trap'] = len(got)
        if got:
            lines.append('\n##### Traps #####')
            for comment, group in got:
                lines += ['', comment] + group

        # --- terrain -----------------------------------------------------
        got, feat_missed = [], []
        for code in sorted(FEAT_ALIAS):
            if code not in codes:
                continue
            if any(k.startswith(code.lower() + ':') for k in tiles['feat']):
                continue

            donor = FEAT_ALIAS[code]
            cells = {k.rsplit(':', 1)[1]: v for k, v in tiles['feat'].items()
                     if k.startswith(donor.lower() + ':')}
            if not cells:
                feat_missed.append(code)
                continue

            got.append(('# as %s' % donor,
                        ['feat:%s:%s:%s:%s' % (code, light, c[0], c[1])
                         for light, c in sorted(cells.items())]))

        counts['feat'] = len(got)
        if got:
            lines.append('\n##### Terrain #####')
            for comment, group in got:
                lines += ['', comment] + group

        print("%-12s %3d monsters (%d on base+colour, %d via an aliased base), "
              "%d objects, %d traps, %d terrain"
              % (ts['directory'], counts['monster'], exact_n, alias_n,
                 counts['object'], counts['trap'], counts['feat']))
        for label, left in (('monsters', missed), ('objects', obj_missed),
                            ('traps', trap_missed), ('terrain', feat_missed)):
            if left:
                print("             no donor for %d %s: %s%s"
                      % (len(left), label, ', '.join(sorted(left)[:4]),
                         ' ...' if len(left) > 4 else ''))

        if dry_run:
            continue

        # A tileset that needs nothing gets nothing.  Writing a header-only
        # file and chaining it into a set with complete coverage adds an
        # include that can never fire and implies a gap that is not there.
        if not lines:
            existing = os.path.join(TILES, ts['directory'], OUTPUT)
            if os.path.exists(existing):
                os.remove(existing)
                print("             removed %s, nothing left to borrow"
                      % OUTPUT)
            continue

        out = os.path.join(TILES, ts['directory'], OUTPUT)
        with open(out, 'w', encoding='utf-8') as f:
            f.write(HEADER % (OUTPUT, ts['pref']))
            f.write('\n'.join(lines) + '\n')

        # And make sure the tileset actually loads it, once.
        pref = os.path.join(TILES, ts['directory'], ts['pref'])
        with open(pref, encoding='utf-8', errors='replace') as f:
            body = f.read()

        if OUTPUT not in body:
            with open(pref, 'a', encoding='utf-8') as f:
                f.write("\n# Load ZangbandTK's stand-in tiles (generated)\n"
                        "%%:%s\n" % OUTPUT)
            print("             added %%:%s to %s" % (OUTPUT, ts['pref']))

    return 0


if __name__ == '__main__':
    sys.exit(main())
