#!/usr/bin/env python3
"""
Build the Neon tileset: one silhouette, one colour, and the colour is data.

Every other tileset paints colour into its art, and the game then throws its
own colour away -- once a graphic tile is assigned, ui-map.c:258 short-circuits
on `da & 0x80` and `color:` never reaches the screen.  So a black hound and a
red one are two drawings there, and a monster whose colour is the only thing
distinguishing it gets whichever drawing somebody made.

Here a tile is a silhouette drawn in exactly one non-black colour, the sheet is
laid out with *the colour on the row and the shape on the column*, and the
preference file is generated by reading each monster's own `base:` and `color:`.
That is the whole idea, and it falls out of the prf format, which has always
been `attr:char` -- which in graphics mode has always meant `row:col`.

What it buys:

  * Thirty-odd breeds of zephyr hound are one drawing, each finally the colour
    monster.txt says it is.  Around 250 silhouettes cover what the 8x8 set
    spends 945 distinct pictures on.
  * The source art is text -- 16 lines of `X` and `.` -- so it diffs in git,
    is reviewable without a paint program, and can be fixed by hand.  The sheet
    is a build artifact.
  * Lighting is free.  Terrain does not spend the tone axis on identity: its
    hue comes from terrain.txt and the tone carries the light, which is the ZX
    Spectrum BRIGHT bit doing the job it always did.

What it costs, and it is a real cost: the game uses 27 colour codes and this
palette has 24 slots that clear the legibility bar against black.  Three pairs
collapse -- Slate/Light Slate, Dark/Light Dark, Mustard/Mud -- each a pair the
eye already struggles with in ASCII.  `--check` measures this rather than
asserting it.

Influence: Jeff Minter / Llamasoft.  Hyper-saturated, and legible precisely
because a tile only ever carries one of these colours at a time.

    scripts/tiles/build-neon.py            build the sheet and the prf
    scripts/tiles/build-neon.py --check    measure the palette and the output
    scripts/tiles/build-neon.py --preview  also write a mock map to look at

Deterministic: no randomness anywhere, so re-running produces a byte-identical
sheet and an empty diff unless something actually changed.

NOTE: read_png/write_png are duplicated from make-terrain.py.  They should be
one shared module; they are not yet because that script is being worked on and
a shared file is the wrong thing to move underneath it.
"""

import collections
import os
import re
import struct
import sys
import zlib

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.normpath(os.path.join(HERE, '..', '..'))
DATA = os.path.join(ROOT, 'lib', 'gamedata')
SRC = os.path.join(HERE, 'neon')
OUT = os.path.join(ROOT, 'lib', 'tiles', 'neon')

TILE = 16
# Brightest first, so a lighting offset is simply a step along this list.
TONES = ('pale', 'neon', 'dim', 'shadow')
MONSTERS = ('monster.txt', 'monster.zangband.txt', 'monster.zangbandtk.txt')


# --- PNG, without a dependency ---------------------------------------------

def read_png(path):
    """Only the flavour of PNG write_png emits: RGBA, depth 8, filter 0."""
    data = open(path, 'rb').read()
    assert data[:8] == b'\x89PNG\r\n\x1a\n', path + ' is not a PNG'
    idat, width, height = b'', 0, 0
    at = 8
    while at < len(data):
        length = struct.unpack('>I', data[at:at + 4])[0]
        kind = data[at + 4:at + 8]
        body = data[at + 8:at + 8 + length]
        if kind == b'IHDR':
            width, height, depth, colour, _, _, interlace = \
                struct.unpack('>IIBBBBB', body)
            assert depth == 8 and colour == 6 and interlace == 0, 'unsupported'
        elif kind == b'IDAT':
            idat += body
        at += 12 + length
    raw = zlib.decompress(idat)
    stride = width * 4
    rows = []
    for y in range(height):
        start = y * (stride + 1)
        assert raw[start] == 0, 'unsupported PNG filter'
        line = raw[start + 1:start + 1 + stride]
        rows.append([tuple(line[x * 4:x * 4 + 4]) for x in range(width)])
    return rows


def write_png(path, pixels):
    height, width = len(pixels), len(pixels[0])
    raw = bytearray()
    for row in pixels:
        raw.append(0)
        for p in row:
            raw += bytes(p)

    def chunk(kind, body):
        return (struct.pack('>I', len(body)) + kind + body
                + struct.pack('>I', zlib.crc32(kind + body) & 0xffffffff))

    out = b'\x89PNG\r\n\x1a\n'
    out += chunk(b'IHDR', struct.pack('>IIBBBBB', width, height, 8, 6, 0, 0, 0))
    out += chunk(b'IDAT', zlib.compress(bytes(raw), 9))
    out += chunk(b'IEND', b'')
    open(path, 'wb').write(out)


# --- colour ----------------------------------------------------------------

def rgb(h):
    return tuple(int(h[i:i + 2], 16) for i in (0, 2, 4))


def _lin(c):
    c /= 255.0
    return c / 12.92 if c <= 0.04045 else ((c + 0.055) / 1.055) ** 2.4


def luminance(h):
    r, g, b = rgb(h)
    return 0.2126 * _lin(r) + 0.7152 * _lin(g) + 0.0722 * _lin(b)


def contrast_on_black(h):
    """A tile is one colour on black, so its legibility *is* this number."""
    return (luminance(h) + 0.05) / 0.05


def lab(h):
    r, g, b = [_lin(v) for v in rgb(h)]
    x = 0.4124 * r + 0.3576 * g + 0.1805 * b
    y = 0.2126 * r + 0.7152 * g + 0.0722 * b
    z = 0.0193 * r + 0.1192 * g + 0.9505 * b

    def f(t):
        return t ** (1.0 / 3) if t > 0.008856 else 7.787 * t + 16.0 / 116

    fx, fy, fz = f(x / 0.95047), f(y), f(z / 1.08883)
    return (116 * fy - 16, 500 * (fx - fy), 200 * (fy - fz))


def delta_e(a, b):
    la, lb = lab(a), lab(b)
    return sum((la[i] - lb[i]) ** 2 for i in range(3)) ** 0.5


# --- inputs ----------------------------------------------------------------

def read_palette():
    """hues in file order, the game-colour map, and the lighting map."""
    hues, attrs, lighting, trap_lighting = {}, {}, {}, {}
    for line in open(os.path.join(SRC, 'palette.txt'), encoding='utf-8'):
        line = line.strip()
        if not line or line.startswith('#'):
            continue
        bits = line.split(':')
        if bits[0] == 'hue':
            hues[bits[1]] = dict(zip(TONES, bits[2:2 + len(TONES)]))
        elif bits[0] == 'attr':
            attrs[bits[1]] = (bits[2], bits[3])
        elif bits[0] == 'lighting':
            lighting[bits[1]] = int(bits[2])
        elif bits[0] == 'trap-lighting':
            trap_lighting[bits[1]] = int(bits[2])
    return hues, attrs, lighting, trap_lighting


def read_shapes():
    """name -> 16 strings of 16 characters, `X` for ink."""
    shapes = {}
    directory = os.path.join(SRC, 'shapes')
    for name in sorted(os.listdir(directory)):
        if not name.endswith('.txt'):
            continue
        rows = []
        for line in open(os.path.join(directory, name), encoding='utf-8'):
            line = line.rstrip('\n')
            if line.startswith('#') or not line.strip():
                continue
            rows.append(line)
        key = name[:-4]
        assert len(rows) == TILE, '%s has %d rows' % (key, len(rows))
        for i, row in enumerate(rows):
            assert len(row) == TILE, '%s row %d is %d wide' % (key, i, len(row))
            assert not set(row) - set('X.'), '%s row %d has stray characters' % (key, i)
        shapes[key] = rows
    return shapes


def read_manifest():
    """The shape each thing is drawn with.

    A `feat:` line may carry a fourth field naming the tone that feature sits
    at when lit; the light then moves it from there.  Without one it sits at
    the tone its colour code maps to.

    It exists because Angband's colours were picked for single glyphs, and a
    glyph's colour spread over a whole cell reads quite differently: FLOOR is
    White and GRANITE is Light Slate, so the floor came out brighter than the
    wall around it.

    An absolute tone rather than a relative shift, because relative shifts
    were tried first and were wrong twice over.  They stack with the lighting
    offset and clamp at the ends, so four ground features starting from four
    base tones all landed on `shadow` together -- black, in practice -- while
    a global darkening step aimed at the walls pushed lava and broken doors
    off the bottom as well.  A target tone cannot do either.
    """
    feats, bases, tvals, traps, gf = {}, {}, {}, {}, {}
    for line in open(os.path.join(SRC, 'manifest.txt'), encoding='utf-8'):
        line = line.strip()
        if not line or line.startswith('#'):
            continue
        kind, key, shape = line.split(':', 2)
        target = None
        if kind == 'feat' and ':' in shape:
            shape, target = shape.rsplit(':', 1)
            assert target in TONES, '%s: %r is not a tone' % (key, target)
        if kind == 'feat':
            feats[key] = (shape, target)
            continue
        {'feat': feats, 'base': bases, 'tval': tvals,
         'trap': traps, 'gf': gf}[kind][key] = shape
    return feats, bases, tvals, traps, gf


def read_records(filename, fields, start='name'):
    """Records from a gamedata file, in file order.

    `start` is the field that begins a record, and it is not always `name:`:
    terrain.txt puts `code:` first, and a reader that assumes otherwise hangs
    every feature's code on the feature before it -- quietly, and with a
    plausible-looking result.
    """
    out, current = [], None
    path = os.path.join(DATA, filename)
    for line in open(path, encoding='utf-8', errors='replace'):
        line = line.rstrip('\n')
        if line.startswith(start + ':'):
            current = {start: line[len(start) + 1:].strip()}
            out.append(current)
        elif current is not None:
            for field in fields:
                if line.startswith(field + ':'):
                    current[field] = line[len(field) + 1:].strip()
    return out


def object_name(fmt):
    """object.txt's `name:` as lookup_sval() will compare it.

    lookup_sval() runs each kind's name through obj_desc_name_format() before
    comparing, so `& Small wooden chest~` is looked up as "Small wooden
    chest".  Emitting the raw form instead produces a preference file that
    parses cleanly and resolves nothing -- there is no error for an sval that
    does not exist, so 157 object lines simply do nothing.  Ported from
    obj_desc_name_format() in src/obj-desc.c with pluralise false and no
    modstr, which is how lookup_sval() calls it.
    """
    out, at = [], 0
    while at < len(fmt):
        ch = fmt[at]
        if ch == '&':
            while at < len(fmt) and fmt[at] in ' &':
                at += 1
            continue
        if ch == '~':                       # singular: drop it
            at += 1
            continue
        if ch == '|':                       # kni|fe|ves| -> knife
            rest = fmt[at + 1:]
            first = rest.find('|')
            second = rest.find('|', first + 1) if first >= 0 else -1
            if first < 0 or second < 0:
                break
            out.append(rest[:first])
            at = at + 1 + second + 1
            continue
        out.append(ch)
        at += 1
    return ''.join(out)


def read_flavours():
    """(index, colour code) for every flavour, plus its tval."""
    names = colour_names()
    out, tval = [], None
    index = 0
    for line in open(os.path.join(DATA, 'flavor.txt'), encoding='utf-8'):
        line = line.strip()
        if line.startswith('kind:'):
            tval = line.split(':')[1]
        elif line.startswith('flavor:') or line.startswith('fixed:'):
            bits = line.split(':')
            index = int(bits[1])
            attr = bits[3] if line.startswith('fixed:') else bits[2]
            code = names.get(_fold(attr))
            if code:
                out.append((index, code, tval))
    return out


def _fold(name):
    """Normalise a colour name for lookup.

    flavor.txt says "Light Green" and projection.txt says "Light dark",
    "ORANGE" and "L_DARK" for the same three ideas.  Folding rather than
    matching exactly is what stops a data file's capitalisation from quietly
    costing a tile -- which it did: one potion flavour was missing until
    `T` (Light Teal) was mapped, and these spellings would have cost more.
    """
    name = name.strip().upper().replace('_', ' ')
    if name.startswith('L '):
        name = 'LIGHT ' + name[2:]
    return ' '.join(name.split())


def colour_names():
    """"Light Green" -> 'G', read from the engine's own table."""
    text = open(os.path.join(ROOT, 'src', 'z-color.c'), encoding='utf-8').read()
    return {_fold(name): code
            for code, name in re.findall(r"\{'(.)',\s*\"([^\"]+)\"", text)}


# --- layout ----------------------------------------------------------------

class Sheet:
    """Colour on the row, shape on the column.

    Thirty rows to a block -- ten hues by three tones -- and a block holds 128
    columns, which is the whole of the coordinate space a prf line can name.
    Four blocks fit, so 512 shapes, against the ~250 a complete set needs.
    """

    def __init__(self, hues):
        self.hues = hues
        self.order = list(hues)
        self.block_rows = len(self.order) * len(TONES)
        self.columns = {}

    def slot(self, hue, tone):
        return self.order.index(hue) * len(TONES) + TONES.index(tone)

    def column(self, shape):
        return self.columns.setdefault(shape, len(self.columns))

    def cell(self, shape, hue, tone):
        index = self.column(shape)
        block, col = divmod(index, 128)
        row = block * self.block_rows + self.slot(hue, tone)
        assert row < 128 and col < 128, 'ran out of coordinate space'
        return row, col

    def size(self):
        blocks = (len(self.columns) + 127) // 128
        cols = min(len(self.columns), 128)
        return cols * TILE, max(blocks, 1) * self.block_rows * TILE

    def render(self):
        width, height = self.size()
        black = (0, 0, 0, 255)
        pixels = [[black] * width for _ in range(height)]
        for shape, index in self.columns.items():
            block, col = divmod(index, 128)
            for hue in self.order:
                for tone in TONES:
                    row = block * self.block_rows + self.slot(hue, tone)
                    ink = rgb(self.hues[hue][tone]) + (255,)
                    for y, line in enumerate(SHAPES[shape]):
                        py = row * TILE + y
                        for x, ch in enumerate(line):
                            if ch == 'X':
                                pixels[py][col * TILE + x] = ink
        return pixels


# --- the preference file ---------------------------------------------------

def build():
    hues, attrs, lighting, trap_lighting = read_palette()
    feats, bases, tvals, traps, gf = read_manifest()
    sheet = Sheet(hues)
    lines, counts = [], {}
    # Which categories each colour ends up carrying.  The distinction matters:
    # a creature must be visible, but remembered unlit terrain is *supposed*
    # to be dim, so one legibility floor for both would be the wrong test.
    used = {}
    # And what asked for each colour, so a failure can say which feature is
    # too dark rather than only which hex value is.
    blame = {}

    names = colour_names()

    def emit(text, shape, colour, kind, shift=0, target=None):
        # The data files spell a colour two ways and neither is wrong: a
        # single-letter code (`graphics:^:R`) or a full name
        # (`graphics:^:light slate`).  trap.txt uses both, five records apart,
        # and a resolver that only took codes emitted nothing for those five
        # -- with no error, because a colour it cannot place just returns.
        code = colour if colour in attrs else names.get(_fold(colour))
        if code not in attrs:
            return False
        hue, base = attrs[code]
        # The light moves the tone; it does not replace it.  Replacing it is
        # what collapsed grass into trees.  `target` overrides where the
        # feature sits when lit, and the light still moves it from there.
        start = TONES.index(target if target else base)
        tone = TONES[max(0, min(len(TONES) - 1, start + shift))]
        row, col = sheet.cell(shape, hue, tone)
        used.setdefault(hues[hue][tone], set()).add(kind)
        blame.setdefault(hues[hue][tone], set()).add(text)
        lines.append('%s:0x%02X:0x%02X' % (text, 0x80 | row, 0x80 | col))
        return True

    # Terrain.  Hue from terrain.txt, tone from the light.
    terrain = read_records('terrain.txt', ('name', 'graphics'), start='code')
    counts['terrain'] = 0
    lines.append('\n##### Terrain #####\n')
    for record in terrain:
        code = record.get('code')
        entry = feats.get(code)
        if not entry or 'graphics' not in record:
            continue
        shape, target = entry
        colour = record['graphics'].split(':')[-1]
        # Lit terrain never sits at `pale`.  Pale is the top of the ramp and
        # what a torch beside you does to a feature; a feature that starts
        # there under ambient light has nowhere brighter to go and reads
        # washed out -- a pale peach door instead of a wooden one.  Angband's
        # light colours (Light Umber, Light Slate and the rest) map to that
        # tone, so without this rule half the dungeon starts at the top.
        if target is None and colour in attrs and attrs[colour][1] == 'pale':
            target = 'neon'
        for light in ('torch', 'los', 'lit', 'dark'):
            kind = 'unlit' if light == 'dark' else 'terrain'
            if emit('feat:%s:%s' % (code, light), shape, colour, kind,
                    lighting[light], target):
                counts['terrain'] += 1

    # Monsters.  Shape from `base:`, colour from `color:`, which is the point.
    lines.append('\n##### Monsters #####\n')
    counts['monsters'] = 0
    for filename in MONSTERS:
        for record in read_records(filename, ('base', 'color')):
            shape = bases.get(record.get('base'))
            colour = record.get('color')
            if shape and colour and emit('monster:%s' % record['name'],
                                        shape, colour, 'monster'):
                counts['monsters'] += 1

    # Objects that carry their own colour.  Flavoured ones do not: before it is
    # identified a potion is its flavour, so those come from flavor.txt below.
    lines.append('\n##### Objects #####\n')
    counts['objects'] = 0
    flavoured = {t for _, _, t in read_flavours()}
    for record in read_records('object.txt', ('type', 'graphics')):
        tval = record.get('type')
        shape = tvals.get(tval)
        if not shape or tval in flavoured or 'graphics' not in record:
            continue
        colour = record['graphics'].split(':')[-1]
        if emit('object:%s:%s' % (tval, object_name(record['name'])),
                shape, colour, 'object'):
            counts['objects'] += 1

    # Traps.  Keyed on trap.txt's code so the four dart traps are one drawing,
    # and named individually so each still gets its own line.
    lines.append('\n##### Traps #####\n')
    counts['traps'] = 0
    for record in read_records('trap.txt', ('graphics',)):
        if ':' not in record['name']:
            continue
        code, specific = record['name'].split(':', 1)
        shape = traps.get(code)
        if not shape or 'graphics' not in record:
            continue
        colour = record['graphics'].split(':')[-1]
        for light in ('torch', 'los', 'lit', 'dark'):
            # A `dark` anything is remembered rather than seen, trap or
            # terrain, and belongs in the tier that has no legibility floor.
            kind = 'unlit' if light == 'dark' else 'trap'
            if emit('trap:%s:%s' % (specific, light), shape, colour, kind,
                    trap_lighting[light]):
                counts['traps'] += 1

    # Spell effects.  Five shapes, and the element is the colour, so every
    # projection in the game is covered by naming each one against them.
    lines.append('\n##### Spell effects #####\n')
    counts['effects'] = 0
    for record in read_records('projection.txt', ('color',), start='code'):
        for direction, shape in sorted(gf.items()):
            if emit('GF:%s:%s' % (record['code'], direction), shape,
                    record.get('color', ''), 'effect'):
                counts['effects'] += 1

    lines.append('\n##### Flavours #####\n')
    counts['flavours'] = 0
    for index, colour, tval in read_flavours():
        shape = tvals.get(tval)
        if shape and emit('flavor:%d' % index, shape, colour, 'flavour'):
            counts['flavours'] += 1

    # Every shape named in the manifest must end up in the sheet.  One that
    # does not means its lines were all dropped, and a dropped line is silent
    # -- this is how the five traps that spell their colour as a name rather
    # than a code were found.
    unused = sorted(set(SHAPES) - set(sheet.columns))
    assert not unused, 'shapes drawn but never used: %s' % unused

    return sheet, lines, used, counts, blame


HEADER = """# graf-neo.prf -- the Neon tileset.
#
# GENERATED by scripts/tiles/build-neon.py, together with 16x16.png beside it.
# Do not edit either by hand: re-running the script overwrites both.
#
# The sheet has the colour on the row and the shape on the column, so every
# line here is (this thing's colour, this thing's silhouette).  The colours are
# read from lib/gamedata -- a monster's own `color:`, a feature's `graphics:`,
# a flavour's entry in flavor.txt -- which is colour the other tilesets discard.
#
# Anything absent has no silhouette yet and renders as its ASCII letter.
"""


def main():
    check = '--check' in sys.argv
    preview = '--preview' in sys.argv

    sheet, lines, used, counts, blame = build()
    os.makedirs(OUT, exist_ok=True)
    width, height = sheet.size()
    write_png(os.path.join(OUT, '16x16.png'), sheet.render())
    with open(os.path.join(OUT, 'graf-neo.prf'), 'w', encoding='utf-8') as f:
        f.write(HEADER + '\n'.join(lines) + '\n')

    print('  %d shapes -> %dx%d sheet (%d rows of colour x %d columns)'
          % (len(sheet.columns), width, height,
             height // TILE, width // TILE))
    for kind in ('terrain', 'monsters', 'objects', 'flavours', 'traps',
                 'effects'):
        print('  %-9s %d' % (kind, counts[kind]))

    if check:
        report(sheet, used, blame)
    if preview:
        make_preview(sheet)
        # And again at actual size.  Brightness cannot be judged at 3x: a
        # colour at 2:1 against black is a discernible dot when it is three
        # pixels wide and simply absent when it is one, which is how the
        # floor and the road shipped invisible.
        make_preview(sheet, zoom=1, filename='preview-actual-size.png')
    return 0


def report(sheet, used, blame):
    hues, attrs = read_palette()[:2]
    print('\n  --- palette ---')
    print('  %d slots carry %d game colour codes' % (len(used), len(attrs)))

    # A tile is one colour on black, so a slot's contrast against black *is*
    # its legibility -- but the bar is not the same for everything on screen.
    # A monster has to be spotted.  Lit terrain has to be visible as ground
    # and should lose to the monster standing on it, which is the entire
    # reason terrain is biased a tone darker than its ASCII colour.  And
    # remembered terrain is memory: dim is what it means.
    TIERS = (('creatures and objects', {'monster', 'object', 'flavour',
                                        'trap', 'effect'}, 3.0),
             ('lit terrain',           {'terrain'},                     2.5),
             ('remembered terrain',    {'unlit'},                       0.0))
    failures = []
    for label, kinds, floor in TIERS:
        slots = [h for h, k in used.items() if k & kinds]
        if not slots:
            continue
        worst = min(slots, key=contrast_on_black)
        print('    %-22s %2d slots, dimmest #%s at %4.1f:1 (floor %.1f)'
              % (label, len(slots), worst, contrast_on_black(worst), floor))
        failures += [(label, h) for h in slots if contrast_on_black(h) < floor]
    if failures:
        for label, h in failures:
            who = sorted(blame.get(h, ()))
            print('    TOO DARK  #%s at %.1f:1 in %s -- %s%s'
                  % (h, contrast_on_black(h), label, ', '.join(who[:4]),
                     ' ...' if len(who) > 4 else ''))
    assert not failures, '%d colours below their tier floor' % len(failures)

    spot = [h for h, k in used.items()
            if k & {'monster', 'object', 'flavour', 'trap', 'effect'}]
    pairs = sorted((delta_e(a, b), a, b)
                   for i, a in enumerate(sorted(spot))
                   for b in sorted(spot)[i + 1:])
    for d, a, b in pairs[:3]:
        print('    closest pair:           #%s / #%s at dE %.1f' % (a, b, d))

    print('\n  --- output ---')
    text = open(os.path.join(OUT, 'graf-neo.prf'), encoding='utf-8').read()
    cells = re.findall(r'0x([0-9A-F]{2}):0x([0-9A-F]{2})', text)
    rows = {int(r, 16) & 0x7f for r, _ in cells}
    cols = {int(c, 16) & 0x7f for _, c in cells}
    print('    %d lines, rows %d-%d, cols %d-%d'
          % (len(cells), min(rows), max(rows), min(cols), max(cols)))
    width, height = sheet.size()
    # The renderer takes the cell index modulo the sheet size rather than
    # complaining, so an out-of-range coordinate draws the wrong picture in
    # silence.  This is the check that catches it.
    assert max(rows) < height // TILE, 'a row is off the sheet'
    assert max(cols) < width // TILE, 'a column is off the sheet'
    print('    every coordinate is inside the sheet')

    # The renderer takes the cell index modulo the sheet size rather than
    # complaining, so an in-range-but-wrong coordinate draws a different
    # picture in silence and an off-the-end one draws a neighbour.  Reading
    # the sheet back is the only check that catches either.
    sheet_px = read_png(os.path.join(OUT, '16x16.png'))
    by_row = {}
    for hue in sheet.order:
        for tone in TONES:
            by_row[sheet.slot(hue, tone)] = rgb(sheet.hues[hue][tone]) + (255,)
    # A shape with no ink at all is legitimate -- an unexplored square is
    # black in every tileset -- so "empty" is only a fault when the shape in
    # that column was supposed to have ink in it.
    by_col = {index: name for name, index in sheet.columns.items()}
    drawn = {name for name, rows in SHAPES.items() if any('X' in r for r in rows)}
    blank = wrong = deliberate = 0
    for r, c in {(int(a, 16) & 0x7f, int(b, 16) & 0x7f) for a, b in cells}:
        inks = {sheet_px[r * TILE + y][c * TILE + x]
                for y in range(TILE) for x in range(TILE)}
        inks.discard((0, 0, 0, 255))
        if not inks:
            if by_col.get(c) in drawn:
                blank += 1
            else:
                deliberate += 1
        elif inks != {by_row[r % sheet.block_rows]}:
            wrong += 1
    print('    %d cells named, %d wrongly empty, %d deliberately blank, '
          '%d the wrong colour'
          % (len({(a, b) for a, b in cells}), blank, deliberate, wrong))
    assert not blank and not wrong, 'the sheet and the prf disagree'

    # lookup_monster() falls back to a substring match, so a misspelled name
    # binds to whatever contains it.  Names here come from the data files, and
    # this is what proves they stayed that way.
    known = set()
    for filename in MONSTERS:
        known |= {r['name'] for r in read_records(filename, ())}
    named = set(re.findall(r'^monster:([^:]+):', text, re.M))
    assert not named - known, 'unknown monsters: %s' % sorted(named - known)[:3]
    # Same trap as the monster names, and the one that actually bit: an sval
    # that does not resolve is not an error, it is a line that does nothing.
    svals = collections.defaultdict(set)
    for r in read_records('object.txt', ('type',)):
        if 'type' in r:
            svals[r['type']].add(object_name(r['name']).lower())
    # Anchored on both cell coordinates: a greedy `(.*):0x` swallows the
    # first of them and every name then looks wrong.
    unresolved = [(t, n) for t, n in re.findall(
                      r'^object:([^:]+):(.*):0x[0-9A-F]{2}:0x[0-9A-F]{2}$',
                      text, re.M)
                  if n.lower() not in svals[t]]
    assert not unresolved, 'object svals that resolve to nothing: %s' % unresolved[:3]
    print('    %d object svals all resolve'
          % len(re.findall(r'^object:', text, re.M)))

    features = {r['code'] for r in read_records('terrain.txt', (), start='code')}
    used_feats = set(re.findall(r'^feat:([^:]+):', text, re.M))
    assert not used_feats - features, 'unknown terrain: %s' % (used_feats - features)
    print('    %d monster names and %d terrain codes all resolve'
          % (len(named), len(used_feats)))


# --- the preview -----------------------------------------------------------
#
# Composed by reading the generated prf and cutting cells out of the generated
# sheet -- not by drawing the shapes again.  That difference is the point: this
# picture exercises the same three steps the game does (name -> attr/char ->
# cell), so if it looks right the tileset is right, and if a coordinate is
# wrong it is wrong here too.

MAP = [
    "gggggggggggggg##################",
    "ggg12345678ggg#....^.....!.=...#",
    "gggggggggggggg#..............,.#",
    "ggMgHgIgSgRgCg#..h...D...k.....#",
    "gggggggggggggg#.......@...*....#",
    "TTTgggwwwwWWWg#...O............#",
    "TTTgggwwwWWWWg#....%......s....#",
    "gggggwwwwWWWWg#..e...b.........#",
    "ggggggggggggg>##################",
]

# Terrain is drawn `lit`; two ranks of water show shallow against deep.
MAP_FEAT = {
    'g': 'GRASS', 'T': 'TREE', 'w': 'WATER', 'W': 'DEEP_WATER',
    '%': 'RUBBLE', '#': 'GRANITE', '.': 'FLOOR', '>': 'DUNGEON',
    '1': 'STORE_GENERAL', '2': 'STORE_ARMOR', '3': 'STORE_WEAPON',
    '4': 'STORE_BOOK', '5': 'STORE_ALCHEMY', '6': 'STORE_MAGIC',
    '7': 'STORE_BLACK', '8': 'HOME', 'M': 'MAGETOWER', 'H': 'HEALER',
    'I': 'INN', 'S': 'MAGESMITH', 'R': 'RECHARGER', 'C': 'CHAOSTOWER',
}
# Real monsters, named exactly as lib/gamedata names them.
MAP_MON = {
    '@': '<player>', 'h': 'fire hound', 'k': 'cave orc',
    'D': 'baby multi-hued dragon', 's': 'poltergeist', ',': 'grey mold',
    'e': 'floating eye', 'b': 'fruit bat',
}
MAP_TRAP = {'^': 'pit'}
MAP_GF = {'*': ('FIRE', 'static')}
MAP_OBJ = {'O': ('chest', 'Small wooden chest')}
# Flavour indices are global across kinds, so they are looked up by tval
# rather than written down -- a hand-picked number quietly draws a ring where
# a potion was meant.
MAP_OBJ_TVAL = {'!': 'potion', '=': 'ring'}

# Two families that differ from each other by nothing but their `color:` line.
# One drawing each; the colours are the game's own.
FAMILIES = [
    ('fire hound', 'cold hound', 'air hound', 'earth hound', 'energy hound',
     'nexus hound', 'vibration hound', 'gravity hound', 'light hound',
     'dark hound', 'water hound', 'impact hound'),
    ('baby blue dragon', 'baby white dragon', 'baby green dragon',
     'baby black dragon', 'baby red dragon', 'baby gold dragon',
     'pseudo-dragon', 'baby multi-hued dragon'),
    ('Oberon, King of Amber', 'Corwin, Lord of Avalon', 'Dworkin Barimen',
     'Mandor, Master of the Logrus', 'The Serpent of Chaos',
     'Jormungand the Midgard Serpent', 'Serpent-Sauron',
     'Yig, Father of Serpents'),
]


def read_prf():
    """The generated file, back in, as the game reads it."""
    out = {k: {} for k in ('monster', 'feat', 'flavor', 'trap', 'GF', 'object')}
    path = os.path.join(OUT, 'graf-neo.prf')
    for line in open(path, encoding='utf-8'):
        m = re.match(r'(monster|feat|flavor|trap|GF|object):(.+)'
                     r':0x([0-9A-F]{2}):0x([0-9A-F]{2})$', line.strip())
        if not m:
            continue
        kind, key, a, c = m.groups()
        cell = (int(a, 16) & 0x7f, int(c, 16) & 0x7f)
        if kind == 'flavor':
            out[kind][int(key)] = cell
        elif kind in ('feat', 'trap', 'GF', 'object'):
            head, tail = key.rsplit(':', 1)
            out[kind][(head, tail)] = cell
        else:
            out[kind][key] = cell
    return out


def make_preview(sheet, zoom=3, filename='preview.png'):
    prf = read_prf()
    first = {}
    for index, _, tval in read_flavours():
        first.setdefault(tval, index)
    map_flavour = {ch: first[tval] for ch, tval in MAP_OBJ_TVAL.items()
                   if tval in first}
    px = read_png(os.path.join(OUT, '16x16.png'))
    missing = []
    widths = {len(row) for row in MAP}
    assert len(widths) == 1, 'the preview map is ragged: %s' % widths

    rows = len(MAP) + 1 + len(FAMILIES)
    cols = max(len(MAP[0]), max(len(f) for f in FAMILIES))
    W, H = cols * TILE * zoom, rows * TILE * zoom
    out = [[(0, 0, 0, 255)] * W for _ in range(H)]

    def blit(cell, tx, ty):
        if cell is None:
            return
        r, c = cell
        for y in range(TILE):
            for x in range(TILE):
                p = px[r * TILE + y][c * TILE + x]
                if p[:3] == (0, 0, 0):
                    continue
                for dy in range(zoom):
                    for dx in range(zoom):
                        out[(ty * TILE + y) * zoom + dy][(tx * TILE + x) * zoom + dx] = p

    def find(table, key):
        if key not in table:
            missing.append(key)
            return None
        return table[key]

    for ty, line in enumerate(MAP):
        for tx, ch in enumerate(line):
            if ch in MAP_FEAT:
                blit(find(prf['feat'], (MAP_FEAT[ch], 'lit')), tx, ty)
                continue
            # Everything else stands on something: town fittings on grass,
            # dungeon contents on floor.
            under = 'GRASS' if tx < 14 else 'FLOOR'
            blit(find(prf['feat'], (under, 'lit')), tx, ty)
            if ch in MAP_MON:
                blit(find(prf['monster'], MAP_MON[ch]), tx, ty)
            elif ch in MAP_TRAP:
                blit(find(prf['trap'], (MAP_TRAP[ch], 'lit')), tx, ty)
            elif ch in MAP_GF:
                blit(find(prf['GF'], MAP_GF[ch]), tx, ty)
            elif ch in MAP_OBJ:
                blit(find(prf['object'], MAP_OBJ[ch]), tx, ty)
            elif ch in map_flavour:
                blit(find(prf['flavor'], map_flavour[ch]), tx, ty)

    for i, family in enumerate(FAMILIES):
        for tx, name in enumerate(family):
            blit(find(prf['monster'], name), tx, len(MAP) + 1 + i)

    path = os.path.join(SRC, filename)
    write_png(path, out)
    print('\n  preview: %s (%dx%d)' % (path, W, H))
    if missing:
        print('  MISSING from the prf: %s' % sorted(set(map(str, missing)))[:6])


SHAPES = read_shapes()

if __name__ == '__main__':
    sys.exit(main())
